### ISSUE TITLE
Brightness of the module graph

### ISSUE THREAD

**Issue by lavolp3** [SpoturDeal/MMM-rain-forecast#1]
I have the feeling the the brightness of the module graph is very low. 
Comparing it to e.g. MMM-forecast-io also having a graph impemented, its visibility behind mirror glass is far worse. Please have a look at the picture.
I tried out fillColor: #6666ff for this example.

![20180510_142238](https://user-images.githubusercontent.com/20084205/40266024-11650d70-5b44-11e8-8280-c8dca31b4697.jpg)

Is it because of the plotting you use?
Any possibility to change it?

**Comment by SpoturDeal** [comment]
Hello Dirk,

I have fixed the "brightless level"  the issue was a filter I planned to use to add millimeters an hour. Never got to make it. If you update the brightness should be OK.
