### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by codac** [SpoturDeal/MMM-rain-forecast#5]
The request library is deprecated (see [here](https://github.com/request/request/issues/3143))

**Comment by SpoturDeal** [comment]
There is a new version now

**Comment by codac** [comment]
a new version of what?

**Comment by SpoturDeal** [comment]
Which request library has been deprecated?

**Comment by codac** [comment]
in your node_helper.js
`var request = require('request')`

**Comment by SpoturDeal** [comment]
just use 

``` npm install -y request```

Then it works.

**Comment by codac** [comment]
Yes I know, but like I said, it is deprecated and is supposed to be replaced by node-fetch for example. Keeping it and using it is no good practice.

**Comment by SpoturDeal** [comment]
You are right, it is not good practice.
