### ISSUE TITLE
Not working for Swedish location

### ISSUE THREAD

**Issue by alexbergsland** [SpoturDeal/MMM-rain-forecast#6]
Hi.
Is this service limited to the Netherlands?
When I check the website (https://www.buienradar.nl/weer/sundby/se/2670883) I get the local forecast, but when I enter coordinates in the config I get a json response on my MM:
![2022-07-08](https://user-images.githubusercontent.com/5063036/178001109-ef96bd6f-95b3-4025-945f-0a5d36ac394b.png)

When I use default coordinates I get a forecast in text (something like "Until 12:15 no rain", meaning the problem is the coordinates.

The coordinates I used where:
```
                lat: 59.4,
                lon: 17.0,
```
I also tried:
```
                lat: 59.388589,
                lon: 17.049531,
```

Also, when I read about their API there is a checkbox for Nederland/België or Europa, could that be that the API is limited to one of them?
https://www.buienradar.nl/overbuienradar/gratis-weerdata

**Comment by SpoturDeal** [comment]
Buienradar is a Dutch rain expectation provider. If you visit www.buienradar.nl and you find a location in the Netherlands, it will show when it is raining.  As far as I know it has a range of about 200km around De Bilt (Utrecht) So most likely Sweden is out of reach.

Maybe in the future they expect a larger area.

**Comment by alexbergsland** [comment]
Thank you for your quick reply.
Maybe I was not clear enough but their service do cover Sweden as I can get a local forecast on their site ([check this link](https://www.buienradar.nl/weer/sundby/se/2670883)), close enough to those coordinates I tried in the config.

I will check your code tonight and see if there is anything I can do.

**Comment by SpoturDeal** [comment]
Thanks again for your message you are right the weather is showing.
The MMM app is **_only_** rain forecast that works withe there 250km radar, and Stockholm or Sundby is over 700km.

You should check[ their website](https://www.buienradar.nl/) when rain is expected you can see the range of the radar, (try Next Monday or Wednesday)

check without setting a location then it is centered on the radar center
