### ISSUE TITLE
No data in app

### ISSUE THREAD

**Issue by rubique1903** [SpoturDeal/MMM-rain-forecast#7]
I get the following error message in the app : {"message":"no Route matched with those values"}

Has the source of buienradar changed ?

Is this the one used in the module ? https://graphdata.buienradar.nl/
Should this be changed to : https://gpsgadget.buienradar.nl/ ?

Example on the website shows : https://gpsgadget.buienradar.nl/data/raintext?lat=51&lon=3

Who can help? Thanks!

**Comment by SpoturDeal** [comment]
@rubique1903 
It seems that buienradar has stopped the json file.
I will update the app back to the old 2018 version that retrieves a text file

**Comment by leongraumans** [comment]
Hey guys, I also saw that error message. I just pulled your latest changes @SpoturDeal , however, I now see "No Data".  Is that still an error, or do I need to update my configuration to support your changes?

**Comment by rubique1903** [comment]
seems to work again, many thanks!
